Newyork branch
haraphat01/newyorktimes pull request #1
Opened 2020-04-07 07:17 UTC by haraphat01

2020-04-13 18:20 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-13 18:37 UTC, mikenath223 requested changes
### Hi Team 👋

Good job on this. @haraphat01  and @uimarshall 
This is quite an inch-perfect representation of the original webpage.👍

However, a few changes need to be made before proceeding: 

- [ ] Required - Kindly add a pull request message, and make it descriptive enough. It should describe the implementations you made in the project.

- [ ] Required - Also kindly ensure you remove the inline comments in your code. If you want to refer to a previous version of your code consider using git history.

- [ ] Required - In addition, remove the inline style that exists in your HTML file.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-13 18:39 UTC, mikenath223 commented on index.html
> +          <img src="images/sat.jpg" alt="dish" style="width: 100%;" />
Kindly remove the inline style that exists here.

2020-04-13 19:56 UTC, haraphat01 commented
This project contains the following features:

- Header, Footers and Main body of the Article

-  Grid Layouts and FlexBox was used

- Embedded video, "More in Astronomy" Section, Most Popular Section


The corrections requested by the TSE has been worked on, kindly revisit the project.

Thank you.

2020-04-13 21:12 UTC, addod19 requested changes
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, you have done a great job working on the changes requested by the previous TSE 👍 However, we need to make a few changes before proceeding. Kindly check comments below:
- The previous TSE made mention of editing the PR. Kindly edit it.
- Kindly enable stickler for the repo by visiting stickler-ci.com
- There are some repeated codes in our CSS file, let us apply the DRY rule


Kindly make these changes and submit another code review 😄 
Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

2020-04-13 21:13 UTC, addod19 commented
## Pull request under review by Daniel Larbi Addo (TSE)

2020-04-13 23:26 UTC, addod19 requested changes
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, we have to address the comments by the TSE's before we can progress. Kindly take time and go through the comments, and if you have any problem, kindly contact me on slack Daniel Larbi Addo

Kindly address the previous comments and submit another code review

2020-04-14 12:17 UTC, mikenath223 requested changes
### Hello again Team  👋

Your project looks inch-perfect. 👌💪


However as stated in the previous review, kindly update your pull request by editing it. 
Simply do this click the three dots icon at the top of the pull request which is circled in red in the screenshot below then click edit, and edit the pull request with a message that describes the implementations you made in this project.[Screenshot]👇
![Inkedice_screenshot_20200414-130953_LI](https://user-images.githubusercontent.com/33323077/79223891-1a301c00-7e52-11ea-9de7-f2f729de66c5.jpg)


Awesome project once more.👏👏

You are almost there.👍

Kindly fix these issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-14 13:01 UTC, uimarshall commented
> ### Hello again Team 👋
> Your project looks inch-perfect. 👌💪
> 
> However as stated in the previous review, kindly update your pull request by editing it.
> Simply do this click the three dots icon at the top of the pull request which is circled in red in the screenshot below then click edit, and edit the pull request with a message that describes the implementations you made in this project.[Screenshot]👇
> ![Inkedice_screenshot_20200414-130953_LI](https://user-images.githubusercontent.com/33323077/79223891-1a301c00-7e52-11ea-9de7-f2f729de66c5.jpg)
> 
> Awesome project once more.👏👏
> 
> You are almost there.👍
> 
> Kindly fix these issue and request another review👍
> Feel free to contact me on slack(michgolden) if you need further clarification.
> 
> HAPPY CODING👨‍💻

Changes affected, Thanks for the awesome review.

2020-04-14 13:07 UTC, mikenath223 approved these changes
### CONGRATULATIONS  TEAM 👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-04-14 14:20 UTC, merged